#!/bin/bash
set -e
echo "Testing pux extension..."
cd ext
bash compile -cp || exit 1
bash run-test -- --testsuite PP --debug || exit 1

echo "Stress testing on extension..."
bash run-test -- --testsuite PP --repeat 10 || exit 1
cd ..
