#!/bin/bash
function statm()
{
    if [[ `uname` == "Darwin" ]] ; then
        stat -f '%m' $1
    elif [[ `uname` == "Linux" ]] ; then
        stat --format '%Y' $1
    fi
}

if [[ ! -e configure || $(statm config.m4) -gt $(statm configure) ]] ; then
    echo "===> Found change, scaffolding..."
    phpize --clean > /dev/null
    phpize || exit 1
fi
if [[ ! -e Makefile || $(statm configure) -gt $(statm Makefile) ]] ; then
    echo "===> Configuring..."
    ./configure > /dev/null || exit 1
fi
echo "===> Cleaning..."
make clean > /dev/null || exit 1
echo "===> Building..."
make clean > /dev/null && make > /dev/null && make install
